Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-docker"
  config.vm.hostname = "alterwaycosmos"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "MY_WORKDIR", "/home/vagrant/share", create: true, :nfs => true
end
